### ISSUE TITLE
Can't run on RPi 4

### ISSUE THREAD

**Issue by fukawi2** [saschaludwig/OnAirScreen#20]
RPi 4 with Raspbian Buster appears to not package `python3-pyqt5.qtwebengine`

This causes error with `start.py`:
```
$ ./start.py 
Traceback (most recent call last):
  File "./start.py", line 47, in <module>
    from mainscreen import Ui_MainScreen
  File "/home/pi/OnAirScreen/mainscreen.py", line 485, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)
```

**Comment by saschaludwig** [comment]
You have to compile it by yourself.
But it's not needed anymore in the lastest branch "weatherwidget".

**Comment by dbeiner** [comment]
> You have to compile it by yourself.

How to do that ?

Thank you !
